apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-data-pv
spec:
  storageClassName: nfs
  claimRef:
    name: opensearch-data-pvc
    namespace: vector-database
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs_share/opensearch
    server: <ip nfs server>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data-pvc
  namespace: vector-database
spec:
  storageClassName: nfs
  volumeName: opensearch-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-0
  namespace: vector-database
  labels:
    app: opensearch-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-0
  serviceName: opensearch-0
  template:
    metadata:
      labels:
        app: opensearch-0
    spec:
      volumes:
        - name: opensearch-storage
          persistentVolumeClaim:
            claimName: opensearch-data-pvc
      containers:
        - name: opensearch-0
          image: opensearchproject/opensearch:2.1.0
          ports:
            - containerPort: 9200
            - containerPort: 9600
          env:
            - name: cluster.name
              value: opensearch-cluster
            - name: node.name
              value: opensearch-node1
            - name: discovery.seed_hosts
              value: opensearch-node1
            - name: cluster.initial_master_nodes
              value: opensearch-node1
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
          resources:
            requests:
              cpu: 4
              memory: 12Gi
            limits:
              cpu: 4
              memory: 12Gi
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-storage
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-node1
  namespace: vector-database
spec:
  selector:
    app: opensearch-0
  type: NodePort
  ports:
    - name: opensearch-api
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30202
    - name: opensearch-cluster
      protocol: TCP
      port: 9600
      targetPort: 9600
      nodePort: 30203

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  namespace: vector-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
        - name: opensearch-dashboards
          image: opensearchproject/opensearch-dashboards:2.1.0
          ports:
            - containerPort: 5601
          env:
            - name: OPENSEARCH_HOSTS
              value: "https://opensearch-node1:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: vector-database
spec:
  selector:
    app: opensearch-dashboards
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: LoadBalancer
